---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - "r-bk"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - "r-bk"
