---
name: Build
on:
  push:
    branches:
      - main
      - "**-ci"
  pull_request:
  schedule:
    - cron: "10 23 * * 3"

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Linear PR history
        if: github.event_name == 'pull_request'
        uses: NexusPHP/no-merge-commits@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Create version file
        run: make version
      - name: Go Lint
        uses: golangci/golangci-lint-action@v8
      - name: Lint
        run: make shellcheck gofmt
        if: runner.os == 'Linux'
      - name: Build
        run: make build
      - name: Show version
        run: ./gh-pr-revision --version
