---
name: Build
on:
  push:
    branches:
      - master
      - "**-ci"
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Create version file
        run: make version
      - name: Lint
        uses: golangci/golangci-lint-action@v6
      - name: Build
        run: make build
      - name: Show version
        run: ./gh-revision --version
